version: '3.4'

networks:
  mqtt:
    external: true

services:
  homebridge:
    image: oznu/homebridge:2023-01-08
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${VOLUMES_PATH}/home-automation/homebridge:/homebridge
    healthcheck:
      test: curl --fail http://localhost:8581 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2023.11.0
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ${VOLUMES_PATH}/home-automation/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    
  mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ${VOLUMES_PATH}/utility-services/mqtt/config:/mosquitto/config
      - ${VOLUMES_PATH}/utility-services/mqtt/data:/mosquitto/data
      - ${VOLUMES_PATH}/utility-services/mqtt/log:/mosquitto/log
    networks:
      - mqtt

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:1.33.2
    container_name: zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mqtt
    ports:
      - 9055:8080
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    networks:
      - mqtt

volumes:
  homebridge:
