version: '3.4'

networks:
  home-automation:
    external: true

services:
  homebridge:
    image: oznu/homebridge:2023-01-08
    container_name: homebridge
    restart: unless-stopped
    ports:
      - 8581:8581/tcp
    environment:
      - TZ=${TIMEZONE}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${VOLUMES_PATH}/home-automation/homebridge:/homebridge
    healthcheck:
      test: curl --fail http://localhost:8581 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    networks:
      - home-automation

volumes:
  homebridge: