version: '3.4'

services:
  homebridge:
    image: oznu/homebridge:2023-01-08
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TIMEZONE}
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - ${VOLUMES_PATH}/home-automation/homebridge:/homebridge
    healthcheck:
      test: curl --fail http://localhost:${HOMEBRIDGE_CONFIG_UI_PORT} || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

volumes:
  homebridge: