version: '3.4'

networks:
  network-services:
    external: true

services:
  wireguard:
    image: weejewel/wg-easy:7
    container_name: wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - WG_HOST=${DOMAIN_URL}
      - PASSWORD=${WIREGUARD_UI_PASSWORD}
      - WG_ALLOWED_IPS=${SERVER_SUBNET}
    volumes:
      - ${VOLUMES_PATH}/network-services/wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - network-services
    healthcheck:
      test: wget -qO- http://localhost:51821 >/dev/null || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  uptime-kuma:
    image: louislam/uptime-kuma:1.23.0
    container_name: uptime-kuma
    ports:
      - 1337:3001
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/network-services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - network-services

  cloudflare:
    image: cloudflare/cloudflared:2023.7.3
    container_name: cloudflare
    environment:
      - PUID=1000
      - PGID=1000
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
    networks:
      - network-services
