version: '3.4'

networks:
  network-services:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11
    container_name: uptime-kuma
    ports:
      - 1337:3001
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/network-services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - network-services
      
  authelia:
    image: authelia/authelia:4.38.3
    container_name: authelia
    ports:
      - 9091:9091
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/network-services/authelia/config:/config
    restart: unless-stopped
    network_mode: host
      
  cloudflare:
    image: cloudflare/cloudflared:2024.2.1
    container_name: cloudflare
    environment:
      - PUID=1000
      - PGID=1000
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    restart: unless-stopped
    networks:
      - network-services
