version: '3.9'

services:
  scprime:
    image: scprime/scprime:1.7.2
    container_name: scprime
    command: -M gctwh --disable-api-security
    environment:
      - PUID=1000
      - PGID=1000
      - SCPRIME_WALLET_PASSWORD=${SCPRIME_WALLET_PASSWORD}
      - SCPRIME_API_PASSWORD=${SCPRIME_API_PASSWORD}
      - TZ=${TIMEZONE}
    ports:
      - 4280:4280
      - 4281:4281
      - 4282:4282
      - 4283:4283
      - 4284:4284
    volumes:
      - ${SCPRIME_METADATA_PATH}:/scp-data
      - ${SCPRIME_DATA_PATH}/space1:/scp1_1
      - ${SCPRIME_DATA_PATH}/space2:/scp1_2
      - ${SCPRIME_DATA_PATH}/space3:/scp1_3
    restart: unless-stopped

  sup-lite:
    image: scprime/supervisor-lite:1.0
    container_name: scprime-supervisor
    command: --api-addr 192.168.0.110:4280 --host-addr=localhost:4282
    environment:
      - TZ=${TIMEZONE}
      - SCPRIME_API_PASSWORD=${SCPRIME_API_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: wget -qO- http://192.168.0.110:4280/host >/dev/null || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

volumes:
  scp-data: