version: '3.9'

networks:
  scprime:
    external: true

services:
  xa-miner:
    image: scprime/xaminer:1.4.14
    container_name: xa-miner
    ports:
      - 8021:8021
      - 4282:4282
      - 42820:42820
      - 4283:4283
      - 8980:80
    environment:
      - PORT=80
      - HOST_ADDR=4282
      - SIAMUX_ADDR=42820
      - HOST_HTTP_API_ADDR=4283
      - HOST_PLATFORM=linux
      - INSTALL_TYPE=Migrate
      - INSTALLER_VERSION=1.3.0
      - SCPRIME_WALLET_PASSWORD=${SCPRIME_WALLET_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${SCPRIME_METADATA_PATH}:/root/.scprime
      - ${XA_MINER_CONFIG_PATH}:/root/scprime
      - ${SCPRIME_DATA_PATH}/space1:/mnt/hdd-scp/space1
      - ${SCPRIME_DATA_PATH}/space2:/mnt/hdd-scp/space2
      - ${SCPRIME_DATA_PATH}/space3:/mnt/hdd-scp/space3
    restart: unless-stopped
    runtime: runc
    networks:
      - scprime