version: '3.9'

services:
  scprime:
    container_name: scprime
    command: -M gctwh
    image: scprime/scprime:1.7.2
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - SCPRIME_WALLET_PASSWORD=${SCPRIME_WALLET_PASSWORD}
      - SCPRIME_API_PASSWORD=${SCPRIME_API_PASSWORD}
    ports:
      - 4280:4280
      - 4281:4281
      - 4282:4282
      - 4283:4283
      - 4284:4284
    volumes:
      - ${SCPRIME_METADATA_PATH}:/scp-data
      - ${SCPRIME_DATA_PATH}/space1:/scp1_1
      - ${SCPRIME_DATA_PATH}/space2:/scp1_2
      - ${SCPRIME_DATA_PATH}/space3:/scp1_3
    restart: unless-stopped

  sup-lite:
    image: scprime/supervisor-lite:1.0
    command: --api-addr 192.168.0.110:4280 --host-addr=localhost:4282
    restart: unless-stopped
    environment:
      - SCPRIME_API_PASSWORD=${SCPRIME_API_PASSWORD}

volumes:
  scp-data: