version: '3.4'
services:
  wireguard:
    image: weejewel/wg-easy:7
    container_name: wireguard
    environment:
      - WG_HOST=${DOMAIN_URL}
      - PASSWORD=${WIREGUARD_UI_PASSWORD}
      - WG_DEFAULT_DNS=1.1.1.1
    volumes:
      - ${VOLUMES_PATH}/utility-services/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: wget -qO- http://localhost:51821 >/dev/null || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  uptime-kuma:
    image: louislam/uptime-kuma:1.21.1
    container_name: uptime-kuma
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "1337:3001"
    restart: unless-stopped