version: '3.4'

networks:
  utility-services:
    external: true
  mqtt:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.8.4
    container_name: homepage
    ports:
      - 3000:3000
    environment:
      - TZ=${TIMEZONE}
      - HOMEPAGE_VAR_SERVER_IP=${SERVER_IP}
      - HOMEPAGE_VAR_SONARR_KEY=${SONARR_API_KEY}
      - HOMEPAGE_VAR_RADARR_KEY=${RADARR_API_KEY}
      - HOMEPAGE_VAR_OVERSEERR_KEY=${OVERSEERR_API_KEY}
      - HOMEPAGE_VAR_BAZARR_KEY=${BAZARR_API_KEY}
      - HOMEPAGE_VAR_DELUGE_PASSWORD=${DELUGE_PASSWORD}
      - HOMEPAGE_VAR_TAUTULLI_KEY=${TAUTULLI_API_KEY}
      - HOMEPAGE_VAR_PORTAINER_KEY=${PORTAINER_API_KEY}
      - HOMEPAGE_VAR_HOMEBRIDGE_USERNAME=${HOMEBRIDGE_USERNAME}
      - HOMEPAGE_VAR_HOMEBRIDGE_PASSWORD=${HOMEBRIDGE_PASSWORD}
      - HOMEPAGE_VAR_HOME_ASSISTANT_KEY=${HOME_ASSISTANT_KEY}
      - HOMEPAGE_VAR_EMAIL=${EMAIL}
      - HOMEPAGE_VAR_UNIFI_PASSWORD=${UNIFI_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/utility-services/homepage/config:/app/config
      - ${MEDIA_HDD_PATH}:/media
      - ${SCPRIME_DATA_PATH}:/scprime-data
    restart: unless-stopped
    networks:
      - utility-services

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    container_name: dockerproxy
    ports:
      - 2375:2375
    environment:
      - CONTAINERS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - utility-services

  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.14.2
    container_name: speedtest-tracker
    ports:
      - 8081:80
      - 8443:443
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - DB_HOST=/config/database.sqlite
    volumes:
      - ${VOLUMES_PATH}/utility-services/speedtest/config:/config
    restart: unless-stopped
    networks:
      - utility-services

  scrutiny:
    image: ghcr.io/analogj/scrutiny:v0.7.2-omnibus
    container_name: scrutiny
    ports:
      - 8082:8080
      - 8086:8086
    environment:
      - TZ=${TIMEZONE}
      - COLLECTOR_CRON_SCHEDULE="0 * * * *"
    volumes:
      - /run/udev:/run/udev:ro
      - ${VOLUMES_PATH}/utility-services/scrutiny/config:/opt/scrutiny/config
      - ${VOLUMES_PATH}/utility-services/scrutiny/influxdb:/opt/scrutiny/influxdb
    cap_add:
      - SYS_RAWIO
    privileged: true
    restart: unless-stopped
    networks:
      - utility-services
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8080/api/health | grep -q 'true'
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    ports:
      - 8300:80
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/filebrowser/database:/database
      - ${VOLUMES_PATH}/utility-services/filebrowser/config:/config
      - /:/srv
    restart: unless-stopped
    networks:
      - utility-services
  
  pairdrop:
    image: linuxserver/pairdrop:1.10.5
    container_name: pairdrop 
    ports:
      - 3003:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=S<TIMEZONE)
      - RATE_LIMIT=false
      - WS_FALLBACK=false
      - DEBUG_MODE=false 
    restart: unless-stopped 
    networks:
      - utility-services

  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:0.7.0-nbxyz2
    container_name: netbootxyz
    volumes:
      - ${VOLUMES_PATH}/utility-services/netbootxyz/config:/config
      - ${VOLUMES_PATH}/utility-services/netbootxyz/assets:/assets
    ports:
      - 3004:3000
      - 69:69/udp
      - 8083:80
    restart: unless-stopped
    networks:
      - utility-services

  mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    volumes:
      - ${VOLUMES_PATH}/utility-services/mqtt/config:/mosquitto/config
      - ${VOLUMES_PATH}/utility-services/mqtt/data:/mosquitto/data
      - ${VOLUMES_PATH}/utility-services/mqtt/log:/mosquitto/log
    networks:
      - mqtt

  pgadmin:
    image: dpage/pgadmin4:8.1
    container_name: pgadmin
    ports:
      - 8677:80
    environment:
      - PUID=1000
      - PGID=1000
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - utility-services

  redis-paperless-ngx:
    image: redis:7.2.4
    container_name: redis-paperless-ngx
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/paperless-ngx/redis:/data
    restart: unless-stopped
    networks:
      - utility-services

  postgres-paperless-ngx:
    image: postgres:16.1
    container_name: postgres-paperless-ngx
    ports:
      - 5432:5432
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${PAPERLESS_POSTGRES_DB}
      - POSTGRES_USER=${PAPERLESS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PAPERLESS_POSTGRES_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/utility-services/paperless-ngx/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - utility-services

  paperless-ngx:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.3.3
    container_name: paperless-ngx
    ports:
      - 8555:8000    
    environment:
      - PAPERLESS_TIME_ZONE=${TIMEZONE}
      - PAPERLESS_REDIS=redis://redis-paperless-ngx:6379
      - PAPERLESS_DBHOST=postgres-paperless-ngx
      - COMPOSE_PROJECT_NAME=paperless
      - PAPERLESS_DBPASS=${PAPERLESS_POSTGRES_PASSWORD}
      - PAPERLESS_OCR_LANGUAGES=ron
      - PAPERLESS_OCR_LANGUAGE=ron
    volumes:
      - ${VOLUMES_PATH}/utility-services/paperless-ngx/paperless-ngx/data:/usr/src/paperless/data
      - ${VOLUMES_PATH}/utility-services/paperless-ngx/paperless-ngx/media:/usr/src/paperless/media
      - ${VOLUMES_PATH}/utility-services/paperless-ngx/paperless-ngx/export:/usr/src/paperless/export
      - ${VOLUMES_PATH}/utility-services/paperless-ngx/paperless-ngx/consume:/usr/src/paperless/consume
    restart: unless-stopped
    networks:
      - utility-services
    depends_on:
      - postgres-paperless-ngx
      - redis-paperless-ngx
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgadmin_data:
