version: '3.4'

networks:
  utility-services:
    external: true

services:
  wireguard:
    image: weejewel/wg-easy:7
    container_name: wireguard
    environment:
      - WG_HOST=${DOMAIN_URL}
      - PASSWORD=${WIREGUARD_UI_PASSWORD}
      - WG_ALLOWED_IPS=${SERVER_SUBNET}
    volumes:
      - ${VOLUMES_PATH}/utility-services/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: wget -qO- http://localhost:51821 >/dev/null || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  uptime-kuma:
    image: louislam/uptime-kuma:1.21.2
    container_name: uptime-kuma
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1337:3001
    restart: unless-stopped
    networks:
      - utility-services

  homepage:
    image: ghcr.io/benphelps/homepage:v0.6.16
    container_name: homepage
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 3000:3000
    volumes:
      - ${VOLUMES_PATH}/utility-services/homepage/config:/app/config
      - ${MEDIA_HDD_PATH}:/media
      - ${SCPRIME_DATA_PATH}:/scprime-data
      - ${BACKUP_PATH}:/backup
    restart: unless-stopped
    networks:
      - utility-services

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - POST=0
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - utility-services

  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.13
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ${VOLUMES_PATH}/utility-services/speedtest/config:/config
    restart: unless-stopped
    networks:
      - utility-services

  supercronic:
    image: ghcr.io/sherbibv/supercronic:0.0.6
    container_name: supercronic
    network_mode: none
    command: supercronic -debug backup-crontab
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${SCPRIME_METADATA_PATH}:/scprime-metadata
      - ${BACKUP_PATH}/scprime:/scprime-backup
      - ${VOLUMES_PATH}/utility-services/homepage:/homepage
      - ${BACKUP_PATH}/homepage:/homepage-backup
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:v0.7.1-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - 8082:8080
      - 8086:8086
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /run/udev:/run/udev:ro
      - ${VOLUMES_PATH}/utility-services/scrutiny/config:/opt/scrutiny/config
      - ${VOLUMES_PATH}/utility-services/influxdb:/opt/scrutiny/influxdb
    restart: unless-stopped
    devices:
      - /dev/sda # 6Tb drive
      - /dev/sdb # SSD
      - /dev/sdc # Media drive
      - /dev/sdd # Backup drive
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8080/api/health | grep -q 'true'
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  duplicati:
    image: lscr.io/linuxserver/duplicati:2.0.6
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/duplicati/config:/config
      - ${VOLUMES_PATH}:/docker-source
      - ${BACKUP_PATH}/duplicati/docker:/docker-backup
      - ${SCPRIME_METADATA_PATH}:/scprime-source
      - ${BACKUP_PATH}/duplicati/scprime:/scprime-backup
    ports:
      - 8200:8200
    restart: unless-stopped