version: '3.4'

services:
  wireguard:
    image: weejewel/wg-easy:7
    container_name: wireguard
    environment:
      - WG_HOST=${DOMAIN_URL}
      - PASSWORD=${WIREGUARD_UI_PASSWORD}
      - WG_ALLOWED_IPS=${SERVER_SUBNET}
    volumes:
      - ${VOLUMES_PATH}/utility-services/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    healthcheck:
      test: wget -qO- http://localhost:51821 >/dev/null || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s

  uptime-kuma:
    image: louislam/uptime-kuma:1.21.2
    container_name: uptime-kuma
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/utility-services/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 1337:3001
    restart: unless-stopped

  homepage:
    image: ghcr.io/benphelps/homepage:v0.6.16
    container_name: homepage
    environment:
      - TZ=${TIMEZONE}
    ports:
      - 3000:3000
    volumes:
      - ${VOLUMES_PATH}/utility-services/homepage/config:/app/config
      - ${MEDIA_HDD_PATH}:/media
      - ${SCPRIME_DATA_PATH}:/scprime-data
      - ${SCPRIME_BACKUP_PATH}:/scprime-backup

  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1
      - POST=0
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.12
    container_name: speedtest-tracker
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - ${VOLUMES_PATH}/utility-services/speedtest/config:/config
    restart: unless-stopped
