version: "3.9"

networks:
  ai-services:
    external: true

services:
  ollama:
     image: ollama/ollama:0.9.0
     container_name: ollama
     ports:
       - 11434:11434
     volumes:
       - ${VOLUMES_PATH}/ai-services/ollama:/root/.ollama
     restart: unless-stopped
     networks: 
       - ai-services
  
  open-webui: 
    image: ghcr.io/open-webui/open-webui:v0.6.14
    container_name: open-webui
    ports:
      - 3011:8080
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BACKEND_URL}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OPENID_PROVIDER_URL=${OPENID_PROVIDER_URL}
      - OAUTH_SCOPES=${OAUTH_SCOPES}
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=${OAUTH_MERGE_ACCOUNTS_BY_EMAIL}
    volumes:
      - ${VOLUMES_PATH}/ai-services/open-webui:/app/backend/data
    restart: unless-stopped
    networks: 
      - ai-services
