version: "3.9"

services:
  ollama:
    image: ollama/ollama:0.3.4
    container_name: ollama
    expose:
      - 11434
    volumes:
      - ${VOLUMES_PATH}/ai-services/ollama:/root/.ollama
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
      
  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - 3010:8080
    environment:
      - OLLAMA_API_BASE_URL=http://${SERVER_IP}:11434/api
    volumes:
      - ${VOLUMES_PATH}/ai-services/ollama-webui/webui:/app/backend/data
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway

  open-webui: 
    image: ghcr.io/open-webui/open-webui:v0.3.12
    container_name: open-webui
    ports:
      - 3011:8080
    environment:
      - OLLAMA_BASE_URL=http://${SERVER_IP}:11434
    volumes:
      - ${VOLUMES_PATH}/ai-services/open-webui:/app/backend/data
    restart: unless-stopped
